### PR TITLE
add ProjectE compat

### PR DESCRIPTION
**Pull request by WaitingIdly**
changes in this PR:
- adds `EntityRandomizer` (for both peaceful and mob lists) and `Transmutation` compat.
- adds examples file and i18n wiki keys for the above compat.

### CODE REVIEW

**Review by brachy84 — COMMENTED** [review]
Is it really necessary to split mob and peaceful entity randomaizer?

**Comment by WaitingIdly** [comment]
no, but i dont see the harm in having them split

**Comment by brachy84** [comment]
I do: confusion, inconvenient and unintuitive

**Comment by WaitingIdly** [comment]
merged the two categories

**Review by brachy84 — APPROVED** [review]

**Pull request merged**
